# Generated by Django 4.2.16 on 2024-12-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(db_column='Age')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(db_column='Age')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('employee', 'Employee')], db_column='Role', default='employee', max_length=10)),
                ('years_of_experience', models.PositiveIntegerField(db_column='Years of Experience')),
                ('position', models.CharField(db_column='Position', max_length=255)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, db_column='Photo', null=True, upload_to='employee_photos/')),
                ('is_fired', models.BooleanField(db_column='Is Fired', default=False)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('passing_score', models.PositiveIntegerField(db_column='Passing Score')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('time_to_complete', models.PositiveIntegerField(db_column='Time to Complete')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('test_date', models.DateField(db_column='Test Date')),
                ('score_achieved', models.PositiveIntegerField(db_column='Score Achieved')),
                ('status', models.CharField(choices=[('passed', 'Пройден'), ('failed', 'Не пройден'), ('in_progress', 'В процессе')], db_column='Status', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(db_column='Attempt Number')),
                ('approved', models.BooleanField(db_column='Approved', null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='Employee ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='app.employee')),
                ('test', models.ForeignKey(blank=True, db_column='Test ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='app.test')),
                ('user', models.ForeignKey(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='app.appuser')),
            ],
            options={
                'verbose_name': 'Результат Теста',
                'verbose_name_plural': 'Результаты Тестов',
                'db_table': 'TestResult',
            },
        ),
        migrations.CreateModel(
            name='TestDeletionRequest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_column='Requested At')),
                ('approved', models.BooleanField(db_column='Approved', null=True)),
                ('requested_by', models.ForeignKey(db_column='Requested By', on_delete=django.db.models.deletion.CASCADE, related_name='test_deletion_requests', to='app.appuser')),
                ('test', models.ForeignKey(db_column='Test ID', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='app.test')),
            ],
            options={
                'verbose_name': 'Запрос на удаление теста',
                'verbose_name_plural': 'Запросы на удаление тестов',
                'db_table': 'TestDeletionRequest',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question_text', models.TextField(db_column='Question Text')),
                ('image', models.ImageField(blank=True, db_column='Image for the Question', null=True, upload_to='question_images/')),
                ('test', models.ForeignKey(db_column='Test ID', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(db_column='Answer Text')),
                ('is_correct', models.BooleanField(db_column='Correct Answer', default=False)),
                ('image', models.ImageField(blank=True, db_column='Image for the Answer', null=True, upload_to='answer_images/')),
                ('question', models.ForeignKey(db_column='Question ID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'Answer',
            },
        ),
    ]
