# Generated by Django 4.2.16 on 2024-11-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(db_column='Age')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full Name', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(db_column='Years of Experience')),
                ('position', models.CharField(db_column='Position', max_length=255)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('age', models.PositiveIntegerField(db_column='Age')),
                ('photo', models.ImageField(blank=True, db_column='Photo', null=True, upload_to='employee_photos/')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('passing_score', models.PositiveIntegerField(db_column='Passing Score')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('time_to_complete', models.PositiveIntegerField(db_column='Time to Complete')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('test_date', models.DateField(db_column='Test Date')),
                ('score_achieved', models.PositiveIntegerField(db_column='Score Achieved')),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(db_column='Attempt Number')),
                ('employee', models.ForeignKey(db_column='Employee ID', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('test', models.ForeignKey(db_column='Test ID', on_delete=django.db.models.deletion.CASCADE, to='app.test')),
                ('user', models.ForeignKey(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
            ],
            options={
                'verbose_name': 'Результат Теста',
                'verbose_name_plural': 'Результаты Тестов',
                'db_table': 'TestResult',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question_text', models.TextField(db_column='Question Text')),
                ('image', models.BinaryField(blank=True, db_column='Image for the Question', null=True)),
                ('test', models.ForeignKey(db_column='Test ID', on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'Question',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(db_column='Role_ID', on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('answer_text', models.TextField(db_column='Answer Text')),
                ('is_correct', models.BooleanField(db_column='Correct Answer')),
                ('image', models.BinaryField(blank=True, db_column='Image for the Answer', null=True)),
                ('question', models.ForeignKey(db_column='Question ID', on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'Answer',
            },
        ),
    ]
