# Generated by Django 4.2.16 on 2024-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(db_column='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(db_column='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.PositiveIntegerField(db_column='Years of Experience'),
        ),
    ]
