# Generated by Django 4.2.16 on 2024-12-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdeletionrequest',
            name='requested_by',
            field=models.ForeignKey(db_column='Requested By', on_delete=django.db.models.deletion.CASCADE, related_name='test_deletion_requests', to='app.employee'),
        ),
    ]
