# Generated by Django 4.2.16 on 2024-11-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_employee_age_remove_employee_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='Employee ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
