# Generated by Django 4.2.16 on 2024-11-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_testresult_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='approved',
            field=models.BooleanField(db_column='Approved', null=True),
        ),
        migrations.CreateModel(
            name='TestDeletionRequest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_column='Requested At')),
                ('approved', models.BooleanField(db_column='Approved', null=True)),
                ('requested_by', models.ForeignKey(db_column='Requested By', on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
                ('test', models.ForeignKey(db_column='Test ID', on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
            options={
                'verbose_name': 'Запрос на удаление теста',
                'verbose_name_plural': 'Запросы на удаление тестов',
                'db_table': 'TestDeletionRequest',
            },
        ),
    ]
