# Generated by Django 4.2.16 on 2024-12-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testresult_approved_testdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_fired',
            field=models.BooleanField(db_column='Is Fired', default=False),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, db_column='Test ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.test'),
        ),
    ]
